### ISSUE TITLE
Cannot find module './dev'

### ISSUE THREAD

**Issue by halidozkilic** [jaewonhimnae/boilerplate-mern-stack#42]
Hi today i got this error do you know what is the problem?
` react-boiler-plate@1.0.0 start C:\Users\Casper\Desktop\boilerplate-mern-stack-master
> node server/index.js

internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module './dev'
Require stack:
- C:\Users\Casper\Desktop\boilerplate-mern-stack-master\server\config\key.js
- C:\Users\Casper\Desktop\boilerplate-mern-stack-master\server\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Casper\Desktop\boilerplate-mern-stack-master\server\config\key.js:4:22)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Casper\\Desktop\\boilerplate-mern-stack-master\\server\\config\\key.js',
    'C:\\Users\\Casper\\Desktop\\boilerplate-mern-stack-master\\server\\index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boiler-plate@1.0.0 start: `node server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boiler-plate@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by halidozkilic** [comment]
I fixed this issue normally i use mongoDB compass and thats why I changed files you can correct version on my github repo which called MERN STACK STARTER.
